function [ r ] = Custom8Sin( t,x )
r=t.a1*sin(t.b1*x+t.c1)...
+ t.a2*sin(t.b2*x+t.c2) ...
+ t.a3*sin(t.b3*x+t.c3)...
+ t.a4*sin(t.b4*x+t.c4)...
+ t.a5*sin(t.b5*x+t.c5)...
+ t.a6*sin(t.b6*x+t.c6)...
+ t.a7*sin(t.b7*x+t.c7)...
+ t.a8*sin(t.b8*x+t.c8);
end

